#!/bin/bash

  gcc -o main main.c
  if [ $? -ne 0 ]; then
      echo "ERROR: Failed to compile main.c"
      exit 1
  fi

  gcc -o tester tester.c
  if [ $? -ne 0 ]; then
      echo "ERROR: Failed to compile tester.c"
      exit 1
  fi

  ./tester > mismatches.txt 2>&1
  
  echo "mismatches file is ready"

  head  mismatches.txt
